/**
 * Report generation: Markdown and HTML output for recon results.
 */

import type { ReconReport, RiskLevel } from "./types";

function riskBadge(level: RiskLevel): string {
  const colors: Record<RiskLevel, string> = {
    high: "#ef4444",
    medium: "#eab308",
    info: "#22c55e",
  };
  return `<span style="background:${colors[level]};color:#000;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600">${level.toUpperCase()}</span>`;
}

function riskEmoji(level: RiskLevel): string {
  return level === "high" ? "🔴" : level === "medium" ? "🟡" : "🟢";
}

/** Generate full Markdown report */
export function generateMarkdown(report: ReconReport): string {
  const lines: string[] = [
    `# ReconForge Security Assessment Report`,
    ``,
    `> **Target:** ${report.target}`,
    `> **Domain:** ${report.domain}`,
    `> **Scan Depth:** ${report.depth}`,
    `> **Mode:** ${report.simulation ? "Simulation" : "Live"}`,
    `> **Generated:** ${report.completedAt}`,
    ``,
    `## Executive Summary`,
    ``,
    `**Risk Score: ${report.riskScore}/100** ${riskEmoji(report.riskLevel)}`,
    ``,
    report.summary,
    ``,
    `### Keywords Analyzed`,
    report.keywords.length
      ? report.keywords.map((k) => `- ${k}`).join("\n")
      : "_None provided_",
    ``,
    `---`,
    ``,
    `## Phase 1: OSINT & Social Engineering Fingerprints`,
    ``,
  ];

  for (const f of report.osint) {
    lines.push(`- **${f.category}** [${f.risk}]: ${f.detail}`);
  }

  lines.push(``, `## Phase 2: Subdomain Enumeration`, ``);
  lines.push(`| Subdomain | Services | IP | Status |`);
  lines.push(`|-----------|----------|-----|--------|`);
  for (const s of report.subdomains) {
    lines.push(
      `| ${s.host} | ${s.services.join(", ")} | ${s.ip} | ${s.status} |`
    );
  }

  lines.push(``, `## Phase 3: Technology Fingerprinting`, ``);
  for (const fp of report.fingerprints) {
    const tech = [fp.server, fp.framework, fp.cms, fp.version]
      .filter(Boolean)
      .join(" / ");
    lines.push(`### ${fp.host}`);
    lines.push(`- **Stack:** ${tech || "Unknown"}`);
    lines.push(`- **Headers:** ${fp.headers.join(", ")}`);
    lines.push(``);
  }

  lines.push(`## Phase 4: Vulnerability Intelligence`, ``);
  for (const v of report.vulnerabilities) {
    lines.push(`### ${v.cve} — ${v.severity.toUpperCase()} (CVSS ${v.cvss})`);
    lines.push(`- **Technology:** ${v.technology}`);
    lines.push(`- **Description:** ${v.description}`);
    lines.push(`- **Remediation:** ${v.remediation}`);
    lines.push(``);
  }

  lines.push(``, `## Phase 5: Intelligence Synthesis`, ``);
  for (const s of report.synthesis) {
    lines.push(`### ${riskEmoji(s.priority)} ${s.title}`);
    lines.push(s.detail);
    lines.push(``);
  }

  lines.push(`---`, ``, `*Report generated by ReconForge — Autonomous Security Reconnaissance*`);

  return lines.join("\n");
}

/** Generate styled HTML report */
export function generateHtml(report: ReconReport): string {
  const md = generateMarkdown(report);

  const osintRows = report.osint
    .map(
      (f) =>
        `<tr><td>${f.category}</td><td>${f.detail}</td><td>${riskBadge(f.risk)}</td></tr>`
    )
    .join("");

  const subdomainRows = report.subdomains
    .map(
      (s) =>
        `<tr><td><code>${s.host}</code></td><td>${s.services.join(", ")}</td><td>${s.ip}</td><td>${s.status}</td></tr>`
    )
    .join("");

  const vulnRows = report.vulnerabilities
    .map(
      (v) =>
        `<tr>
          <td><code>${v.cve}</code></td>
          <td>${riskBadge(v.severity)}</td>
          <td>${v.technology}</td>
          <td>${v.cvss}</td>
          <td>${v.description}</td>
          <td class="remediation">${v.remediation}</td>
        </tr>`
    )
    .join("");

  const synthesisBlocks = report.synthesis
    .map(
      (s) =>
        `<div class="insight ${s.priority}"><h4>${riskEmoji(s.priority)} ${s.title}</h4><p>${s.detail}</p></div>`
    )
    .join("");

  const scoreColor =
    report.riskLevel === "high"
      ? "#ef4444"
      : report.riskLevel === "medium"
        ? "#eab308"
        : "#22c55e";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ReconForge Report — ${report.domain}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0a0e17; color: #e2e8f0; padding: 2rem; line-height: 1.6; }
    .header { border-bottom: 2px solid #00ff88; padding-bottom: 1.5rem; margin-bottom: 2rem; }
    h1 { color: #00ff88; font-size: 1.8rem; }
    h2 { color: #38bdf8; margin: 2rem 0 1rem; border-left: 3px solid #38bdf8; padding-left: 0.75rem; }
    .meta { color: #94a3b8; font-size: 0.9rem; margin-top: 0.5rem; }
    .score-card { background: #111827; border: 1px solid #1e293b; border-radius: 12px; padding: 1.5rem; margin: 1.5rem 0; display: flex; align-items: center; gap: 2rem; }
    .score-value { font-size: 3rem; font-weight: 800; color: ${scoreColor}; }
    .score-label { color: #94a3b8; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.1em; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }
    th { background: #1e293b; color: #00ff88; text-align: left; padding: 0.75rem; }
    td { padding: 0.75rem; border-bottom: 1px solid #1e293b; }
    tr:hover td { background: #111827; }
    code { background: #1e293b; padding: 2px 6px; border-radius: 4px; font-size: 0.85rem; color: #38bdf8; }
    .insight { background: #111827; border-radius: 8px; padding: 1rem; margin: 0.75rem 0; border-left: 4px solid #22c55e; }
    .insight.high { border-left-color: #ef4444; }
    .insight.medium { border-left-color: #eab308; }
    .insight h4 { margin-bottom: 0.5rem; }
    td.remediation { font-size: 0.85rem; color: #cbd5e1; max-width: 28rem; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #1e293b; color: #64748b; font-size: 0.8rem; text-align: center; }
    @media print { body { background: white; color: black; } .score-card { border: 1px solid #ccc; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>ReconForge Security Assessment</h1>
    <div class="meta">
      Target: <strong>${report.target}</strong> · Domain: <strong>${report.domain}</strong><br>
      Depth: ${report.depth} · Mode: ${report.simulation ? "Simulation" : "Live"} · ${report.completedAt}
    </div>
  </div>

  <div class="score-card">
    <div>
      <div class="score-label">Risk Score</div>
      <div class="score-value">${report.riskScore}</div>
    </div>
    <div>
      <p>${report.summary}</p>
    </div>
  </div>

  <h2>Phase 1 — OSINT Fingerprints</h2>
  <table><thead><tr><th>Category</th><th>Detail</th><th>Risk</th></tr></thead><tbody>${osintRows}</tbody></table>

  <h2>Phase 2 — Subdomain Enumeration</h2>
  <table><thead><tr><th>Subdomain</th><th>Services</th><th>IP</th><th>Status</th></tr></thead><tbody>${subdomainRows}</tbody></table>

  <h2>Phase 3 — Technology Fingerprinting</h2>
  <table><thead><tr><th>Host</th><th>Stack</th><th>Headers</th></tr></thead><tbody>
    ${report.fingerprints
      .map(
        (fp) =>
          `<tr><td><code>${fp.host}</code></td><td>${[fp.server, fp.framework, fp.cms, fp.version].filter(Boolean).join(" / ")}</td><td>${fp.headers.join(", ")}</td></tr>`
      )
      .join("")}
  </tbody></table>

  <h2>Phase 4 — Vulnerability Intelligence</h2>
  <table><thead><tr><th>CVE</th><th>Severity</th><th>Technology</th><th>CVSS</th><th>Description</th><th>Remediation</th></tr></thead><tbody>${vulnRows}</tbody></table>

  <h2>Phase 5 — Intelligence Synthesis</h2>
  ${synthesisBlocks}

  <div class="footer">Report generated by ReconForge — Autonomous Security Reconnaissance</div>
</body>
</html>`;
}

/** Attach markdown and HTML to report */
export function enrichReport(report: ReconReport): ReconReport {
  return {
    ...report,
    markdown: generateMarkdown(report),
    html: generateHtml(report),
  };
}
